spring.application.name=gtu-driver-tracker
server.port=${SERVER_PORT:8081}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST:discovery-server}:${EUREKA_SERVER_PORT:8761}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false